= はじめに

　ケモインフォマティクス(Chemoinformatics)とは、主に化学に関連するデータをコンピューターを用いて解析し、様々な課題を解くために用いる方法論のことを指し、例えば薬剤の効果と化合物の形状との関連性を解析したり、大量の化合物情報の可視化、クラスタリングなどの多岐にわたるプロセスで活用されています。ケモインフォマティクスという言葉は1990年終わりから2000年はじめに定義され、現在では製薬業界でも薬学系のアカデミアでも必要な技術として認識されています。
　現在現在ディープラーニング(Deep Learning)やAIの利用が盛んですが、創薬を含んだライフサイエンスの分野においてももちろん同様です。
　創薬化学の領域の事例ですと、活性や物性を予測するQSAR（構造活性相関）への応用のみならず、学習したデータに基づいて新しい構造を提案するDe novo generatorへの応用、化合物をどのように作るかといった合成経路の解析へのAIの適用など、創薬サイクルすなわちデザイン（分子設計）、メイク（設計した分子の合成）、テスト（評価）、アナリシス（結果の分析）の各ステップでいかに応用するかといった研究が盛んに行われています。
　どのような化合物を作るべきか、どのように化合物を合成するか、といったことを考えるプロセスはサイエンスと想像力が求められる領域であり、なかなか人以外が担うのは難しい領域であると認識されていましたが、そこへのAIの活用が研究されるようになってきており、最近では国主導のAI創薬人材育成プログラムや産官学のコンソーシアムが立ち上がるくらい盛り上がりをみせています。

　このようにケモインフォマティクスは様々な場面で利用されていますが、今までは関連情報法があまり見つかりませんでした。これはケモインフォマティクス自体の進化の速度が早いことも一因ですが、オープンソースのツールが存在しなかったというのが一番大きな原因と考えています。しかし、ここ数年で、バイオインフォマティクス同様、ケモインフォマティクスもオープンソースでだれでも自由に使えるツールとデータベースが充実してきており、ウェブで検索すれば多くの情報がすぐに取得でき、自己学習することは可能となってきました。ですが、最初の一歩を踏み出すための書籍というものも必要だと考えています。
　
　そこで、ケモインフォマティクスに関する基礎から、それらを応用できるようになるように考えてみました。特に「AI創薬」で用いられるディープラーニングまでを説明しています。

