= ケモインフォマティクスのための環境を整えよう

　本書を読み進めるにあたり必要な環境構築を行いましょう。
本書の実行環境はPython3.6を想定しています。まずはこれ以降のコードを実行できるように環境を構築しましょう！

== Anacondaとは

　今回用いるプログラミング言語Pythonはケモインフォマティクスに限らず多くの有用なライブラリが用意されています。また言語自体も非常にわかりやすく学習コストが低いのがメリットです。
　しかしながら、それらのライブラリの多くは標準のPythonに付属しておらず多くを自分でインストールする必要があります。プログラミングに精通している方にとっては大した問題ではありませんが、初学者にとって勉強するための環境構築がハードルになることは大変苦痛です。コレを回避する手段の一つがAnacondaです。AnacondaはPythonとよく使うライブラリを一纏めにし提供する便利なパッケージです。これを利用することで、機械学習に必要なライブラリが入った環境がすぐに構築できます。
　 Pythonには大きく2.x系のバージョンと3.x系のバージョンとがあります。しかしながら、2.x系はサポートが2020年までとなっているのと、主要なライブラリは3.x系でも動くのであえて２を使う必要性はないと思います。本書でも以下は3.x系を使うこと前提で話を進めていきます。
link:  https://pythonclock.org/

== Anacondaのインストール方法

　 では早速Anacondaをインストールしましょう。アナコンダの公式サイトにアクセスし、ご自身の環境にあったインストーラーをダウンロードします。

link: https://www.anaconda.com/
　 上でも申し上げましたように３系が良いのでPython3.7version(201901現在)のインストーラーをダウンロードします。　ついでLinuxであれば、ターミナルからインストーラーを実行します。
  
[source, bash]
----
bash ~/Downloads/Anaconda3-4.1.0-Linux-x86_64.sh
----

その後インストーラーが起動し色々聞かれると思いますが、基本的にエンターまたはYesで進めていけば良いです。