= ケモインフォマティクスのための環境を整えよう

本書を読み進めるにあたり必要な環境構築を行いましょう。
本書の実行環境はPython3.6を想定しています。

== Anacondaとは

Anacondaとは、機械学習を行うための準備を限りなく楽にするためのパッケージで、これを利用することで、機械学習をすぐに始められるようになります。

=== Q&A

なぜAnacondaを利用するのか？::
  機械学習で広く用いられているプログラミング言語Pythonは多くの有用なライブラリが用意されており、言語自体も非常にわかりやすく学習コストが低いために、ケモインフォマティクスに限らず多くの場面で使われています。しかしながら、それらのライブラリの多くは標準のPythonに付属しておらず自分でインストールする必要があります。プログラミングに精通している方にとっては大した問題ではありませんが、初学者や単純に機械学習をするためPythonを導入したい方には環境構築は大変苦痛な作業です。Anacondaを利用することで、このプログラミング環境の構築作業の手間を大幅に削減することができます。
Pythonには大きく2.x系のバージョンと3.x系のバージョンとがありますが?::
  link:https://pythonclock.org/[2.x系はサポートが2020年までとなっている]のであえて新規にPythonを学ぶ方は2.x系を使う必要は必要性はありません。

== Anacondaのインストール方法

では早速Anacondaをインストールしましょう。link:https://www.anaconda.com/[アナコンダの公式サイト]にアクセスし、ご自身の環境にあったインストーラー(Python3.7version(201901現在))をダウンロードします。　ついでLinuxであれば、ターミナルからインストーラーを実行します。

[source, bash]
----
$ bash ~/Downloads/Anaconda3-4.1.0-Linux-x86_64.sh
----

インストーラーが起動し色々聞かれると思いますが、基本的にエンターまたはYesで進めていけば良いです。

Anacondaのインストールが完了すると、コマンドプロンプトまたはターミナルから'conda'コマンドが使えるようになるはずです。

== Packageのインストール

今回はPython3.6の環境を構築し作業を進めていきたいと思いますので下記のような手順で環境を作ります。-nの後ろは皆さんの好きな名前でも構いません。環境構築後、以後のセッションで利用するツールキットも入れていきます。

[source, bash]
----
$ conda create -n py4chemoinformatics python3.6
$ source activate py4chemoinformatis

# install packages
$ conda install -c conda-forge rdkit
$ conda install -c conda-forge seaborn
$ conda install -c conda-forge ggplot
----

=== インストールしたパッケージの説明

==== RDKit

RDKitはケモインフォマティクスの分野で最近よく用いられるツールキットの一つです。オープンソースソフトウェア（OSS)と呼ばれるものの一つで、商用のものと異なり無料で利用することが可能です。
Greg Landorum氏により開発されており、彼いわく

[quote, Greg Landorum]
RDKitはケモインフォマティクスにおけるSwiss Army Knifeであり、様々な機能のピースの集合体である

これはまさに的を得た表現です。

link:https://www.rdkit.org/docs/[公式ドキュメント]を見ていただくとその多機能さがわかるかと思います。さらに、本ツールキットは開発やユーザーコミュニティの活動も活発であり、最近日本語での解説サイトも増えてきており初学者の導入のハードルも低くなってきています。

=== seaborn

link:https://seaborn.pydata.org/[統計データの視覚化のためのパッケージ]の一つです。

=== ggplot

グラフ描画パッケージの一つで**一貫性のある文法で合理的に描ける**ことが特徴です。もともとはRという統計解析言語のために開発されましたが、yhatという会社によりlink:http://ggplot.yhathq.com/[Pythonに移植]されました。


=== Condaについてもう少し詳しく

先に説明したAnacondaでインストールされるデフォルトのPythonのージョンは3.7ですが、本書執筆時点でconda-forgeで配布されているRDKitのパッケージはpy36となっています。従って最初にPython3.6の環境を構築しました。

なぜ仮想環境を作るのでしょうか::
 Pythonには複数のバージョンと、多くのパッケージがあります。PythonはLinuxやMacOsでは基幹システムにも使われています。ここにパッケージをインストールし、色々変更を加えることは重要な環境に影響を及ぼす危険性があります。実験的にあるパッケージを試してみたいというときもあるでしょう。このような要望に仮想環境はうってつけです。試したいときに試したいパッケージだけを集めたPythonの環境を準備でき試行錯誤できます。テストが終わり不要になれば消すことも容易です。もちろん、良いものができればそのまま利用し続けることも可能です。基幹システムの環境を汚染せず、必要なものを集めてテストできる環境を構築する。ここに仮想環境の価値があると思います。
最後にcondaに関してもう少し詳しく説明します。

[source, bash]
----
# install package
$ conda install <package name>
 
# 仮想環境の作成。
$ conda create -n 仮想環境の名前 python=バージョン
 
# 作った仮想環境一覧の表示
$ conda info -e
 
# 仮想環境の削除
$ conda remove -n 仮想環境の名前
 
# 仮想環境を使う
# mac/linuxの場合
$ source activate 仮想環境の名前
 
# 仮想環境を使う
# windowsの場合
$ activate 仮想環境の名前
 
# 仮想環境から出る
$ source deactivate
 
# 今使っている仮想環境にインストールされているライブラリの一覧を表示
$ conda list
----
