= ケモインフォマティクスのための環境を整えよう
　本書を読み進めるにあたり必要な環境構築を行いましょう。
本書の実行環境はPython3.6を想定しています。まずはこれ以降のコードを実行できるように環境を構築しましょう！

== Anacondaとは
　今回用いるプログラミング言語Pythonはケモインフォマティクスに限らず多くの有用なライブラリが用意されています。また言語自体も非常にわかりやすく学習コストが低いのがメリットです。
　しかしながら、それらのライブラリの多くは標準のPythonに付属しておらず多くを自分でインストールする必要があります。プログラミングに精通している方にとっては大した問題ではありませんが、初学者にとって勉強するための環境構築がハードルになることは大変苦痛です。コレを回避する手段の一つがAnacondaです。AnacondaはPythonとよく使うライブラリを一纏めにし提供する便利なパッケージです。これを利用することで、機械学習に必要なライブラリが入った環境がすぐに構築できます。
　Pythonには大きく2.x系のバージョンと3.x系のバージョンとがあります。しかしながら、2.x系はサポートが2020年までとなっているのと、主要なライブラリは3.x系でも動くのであえて２を使う必要性はないと思います。本書でも以下は3.x系を使うこと前提で話を進めていきます。
link:  https://pythonclock.org/

== Anacondaのインストール方法
　では早速Anacondaをインストールしましょう。アナコンダの公式サイトにアクセスし、ご自身の環境にあったインストーラーをダウンロードします。
link: https://www.anaconda.com/
　上でも申し上げましたように３系が良いのでPython3.7version(201901現在)のインストーラーをダウンロードします。　ついでLinuxであれば、ターミナルからインストーラーを実行します。
  
[source, bash]
----
bash ~/Downloads/Anaconda3-4.1.0-Linux-x86_64.sh
----

その後インストーラーが起動し色々聞かれると思いますが、基本的にエンターまたはYesで進めていけば良いです。
　Anacondaのインストールが完了すると、コマンドプロンプトまたはターミナルから'conda'コマンドが使えるようになるはずです。下記によく使うコマンドをまとめます。

[source, bash]
----
# install package
$ conda install <package name>
 
# 仮想環境の作成。
$ conda create -n 仮想環境の名前 python=バージョン
 
# 作った仮想環境一覧の表示
$ conda info -e
 
# 仮想環境の削除
$ conda remove -n 仮想環境の名前
 
# 仮想環境を使う
# mac/linuxの場合
$ source activate 仮想環境の名前
 
# 仮想環境を使う
# windowsの場合
$ activate 仮想環境の名前
 
# 仮想環境から出る
$ source deactivate
 
# 今使っている仮想環境にインストールされているライブラリの一覧を表示
$ conda list
----

== Packageのインストール
　今回はPython3.6の環境を構築し作業を進めていきたいと思いますので下記のような手順で環境を作ります。-nの後ろは皆さんの好きな名前でも構いません。環境構築後、以後のセッションで利用するツールキットも入れていきます。後でそれぞれのパッケージ関して簡単に説明します。

[source, bash]
----
$ conda create -n py4chemoinformatics python3.6
$ source activate py4chemoinformatis

# install packages
$ conda install -c conda-forge rdkit
$ conda install -c conda-forge seaborn
----

=== RDKit
　RDKitはケモインフォマティクスの分野で最近よく用いられるツールキットの一つです。オープンソースソフトウェア（OSS)と呼ばれるものの一つで、商用のものと異なり無料で利用することが可能です。開発者Greg Landorum氏がRDKITはケモインフォマティクスにおけるSwiss Knifeである。様々な機能のピースの集合体であると述べていました。まさに的を得た表現で、RDKitはケモインフォマティクスに利用する様々な機能をもっています。公式のドキュメントを見ていただくとその多機能さがわかるかと思います。本ツールキットは開発やユーザーコミュニティの活動も活発です。最近日本語での解説サイトも増えてきており初学者の導入のハードルも低くなってきています。
　もちろんケモインフォマティクスのOSSはRDKitに限りません。他にもよく知られているものとしてはOpenBabel, Indigo, CDKなどがあります。それぞれ似たような機能から、異なる機能まで取り揃えていますので、実際の解析に利用したい機能をどのツールキットが持っているかによって使い分けることもできるでしょう。
　
link: 
link:
link:
linl: