== 2章: ケモインフォマティクスのための環境を整えよう

本書を読み進めるにあたり必要な環境構築を行いましょう。
本書の実行環境はPython3.6を想定しています。

=== Anacondaとは

Anacondaとは、機械学習を行うための準備を限りなく楽にするためのパッケージで、これを利用することで、機械学習をすぐに始められるようになります。

==== Q&A

なぜAnacondaを利用するのか？::
  機械学習で広く用いられているプログラミング言語Pythonは多くの有用なライブラリが用意されており、言語自体も非常にわかりやすく学習コストが低いために、ケモインフォマティクスに限らず多くの場面で使われています。しかしながら、それらのライブラリの多くは標準のPythonに付属しておらず自分でインストールする必要があります。プログラミングに精通している方にとっては大した問題ではありませんが、初学者や単純に機械学習をするためPythonを導入したい方には環境構築は大変苦痛な作業です。Anacondaを利用することで、このプログラミング環境の構築作業の手間を大幅に削減することができます。
Pythonには大きく2.x系のバージョンと3.x系のバージョンとがありますが?::
  link:https://pythonclock.org/[2.x系はサポートが2020年までとなっている]のであえて新規にPythonを学ぶ方は2.x系を使う必要は必要性はありません。

=== Anacondaのインストール方法

では早速Anacondaをインストールしましょう。link:https://www.anaconda.com/[公式サイト]にアクセスし、ご自身の環境にあったインストーラー(Python3.7version(201901現在))をダウンロードします。OSがLinuxであればターミナルからインストーラーを実行します。

[source, bash]
----
$ bash ~/Downloads/Anaconda3-4.1.0-Linux-x86_64.sh
----

インストーラーが起動しいくつかの質問をされますが、基本的にエンターまたはYesで進めてください。

Anacondaのインストールが完了すると、コマンドプロンプトまたはターミナルから'conda'コマンドが使えるようになるはずです。

=== Packageのインストール

今回はPython3.6の環境を構築し作業を進めていくので次の手順で開発環境を構築します。コマンドの-nの後ろは"py4chemoinformatics"としていますが皆さんの好きな名前でも構いません。
環境構築後、本章以降で利用するパッケージをインストールします。

[source, bash]
----
$ conda create -n py4chemoinformatics python3.6
$ source activate py4chemoinformatis

# install packages
$ conda install -c conda-forge rdkit
$ conda install -c conda-forge seaborn
$ conda install -c conda-forge ggplot
$ conda install -c conda-forge git
----

=== インストールしたパッケージの説明

==== RDKit

RDKitはケモインフォマティクスの分野で最近よく用いられるツールキットの一つです。オープンソースソフトウェア(OSS)と呼ばれるものの一つで、無償で利用することが可能です。詳しくはlink:ch01_introduction.asciidoc[はじめに]を参照してください。

==== seaborn

link:https://seaborn.pydata.org/[統計データの視覚化のためのパッケージ]の一つです。

==== ggplot

グラフ描画パッケージの一つで**一貫性のある文法で合理的に描ける**ことが特徴です。もともとはRという統計解析言語のために開発されましたが、yhatという会社によりlink:http://ggplot.yhathq.com/[Pythonに移植]されました。

==== Git

バージョン管理システムです。本書ではGitについては説明しませんのでもしGitについて全然知らないという方はlink:https://backlog.com/ja/git-tutorial/[サルでもわかるGit入門]でも読みましょう。

「はじめに」でも説明しましたが、以下のコマンドでpdfを含む全てのデータがダウンロードされますので必要に応じてダウンロードしてください。

[source, bash]
----
$ git clone https://github.com/Mishima-syk/py4chemoinformatics.git
----

=== Condaについてもう少し詳しく

先に説明したAnacondaでインストールされるデフォルトのPythonのージョンは3.7ですが、本書執筆時点で配布されている最新のRDKitはPython3.6を必要とします。このためcondaで仮想環境を構築し、必要なバージョンのPythonをインストールしました。

なぜ仮想環境を作るのでしょうか::
 いくつかのシステムでは様々な機能を提供するために内部的にPythonを利用しているため、特定のパッケージのためにPythonのバージョンを変更してしまうと問題が起こることがあります。仮想環境はこのような問題を解決します。もし、パッケージが異なるライブラリのバージョンを要求しても仮想的なPython環境を準備して試行錯誤できます。不要になれば仮想環境を簡単に削除でき、もとの環境にトラブルを持ちこむこともありません。このように、ひとつのシステム内にそれぞれ個別の開発環境を作成できるようにすることで開発時によく起こるライブラリの依存問題やPythonのバージョンの違いに悩まされることがなくなります。

本書では本書用に一つだけ仮想環境を用意しますが、実際はいくつもの仮想環境をつくって開発することが多いです。そのため、よく利用するcondaのサブコマンドを挙げておきます。

[source, bash]
----
$ conda install <package name>　# install package
$ conda create -n 仮想環境の名前 python=バージョン　# 仮想環境の作成。
$ conda info -e # 作った仮想環境一覧の表示
$ conda remove -n 仮想環境の名前 # 仮想環境の削除
$ source activate 仮想環境の名前 # 仮想環境を使う(mac/linux)
$ activate 仮想環境の名前 # 仮想環境を使う(Windows)
$ source deactivate # 仮想環境から出る
$ conda list # 今使っている仮想環境にインストールされているライブラリの一覧を表示
----

<<<
