== ケモインフォマティクスのための公開データベース

この章ではケモインフォマティクスでよく使うデータベースを紹介します。

.化合物関連データベースの歴史
****
そもそも公共の化合物関連のデータベースというものは歴史が浅いです。では化合物関連データベース自体の歴史が浅いのかと言われれば全然そんなことはなく、昔から色々なデータベースが存在しました。問題はほぼ全てが商用のサービスであったということで、オープンな化合物データベースが登場したのは実はごく最近のことです。アミノ酸、塩基配列、蛋白質結晶構造などのデータベースがかなり以前から無償で提供されていたのに比べると、公開データベースがないという状況はオープンネスを失わせる要員の一つであったと言えるでしょう。
****

=== ChEMBL

link:https://www.ebi.ac.uk/chembl/[ChEMBL]はEBIのChEMBLチームにより維持管理されている医薬品及び開発化合物の結合データ、薬物動態、薬理活性を収録したデータベースです。データは主にメディシナルケミストリ関連のジャーナルから手動で抽出されており、大体3,4ヶ月に一度データの更新があります。

メディシナルケミストリ関連のジャーナルからデータを収集しているため、QSARに関連する情報や背景知識を論文そのものに求めることが可能であり、創薬研究をする際には有用です。

.ChEMBLの秘密
****
ChEMBLはもともとはstARLITeという商用のデータベースだったはずです。（要出典）
****

=== PubChem

link:https://pubchem.ncbi.nlm.nih.gov/[PubChem]はNCBIにより維持管理されている低分子化合物とその生物学的活性データを収録している公開リポジトリです。5000万件以上の化合物情報と、100万件を超えるアッセイデータを含みそのデータ量の多さが特徴とも言えます。もうひとつの特徴はデータをアカデミアからの化合物登録や圧制結果の登録により成長することであり、ここが先のChEMBLとの大きな違いであるといえます。

特にPubChemは初期スクリーニングのデータが多いため、そのようなデータに対しなんらかのマイニングや分析を行いたい場合は有用だと考えられる。

=== どちらを使うべき?

QSARをやりたい場合にはやはりChEMBLのデータを利用することが多いです。IC50のようなデータが得られていることが多いですし、モデルの解釈に元論文をあたることができるというのが大きな理由です。

=== その他有用なデータベース

のちほど追記していきます。IssueやPRでも受け付けてます。

<<<
